version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/solardb
      - JWT_SECRET=your_jwt_secret
      - INFURA_PROJECT_ID=YOUR_INFURA_PROJECT_ID
      - CONTRACT_ADDRESS=YOUR_CONTRACT_ADDRESS
      - WALLET_ADDRESS=YOUR_WALLET_ADDRESS
      - PRIVATE_KEY=YOUR_PRIVATE_KEY
    depends_on:
      - mongo

volumes:
  mongo-data:
